name: Build and Test
on:
  push:
    branches-ignore:
    - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-22.04, windows-2022, macos-14 ]
        java-distribution: [temurin]
        java-version: [ 17, 21 ]
    runs-on: ${{ matrix.os }}
    concurrency:
      group: build-ci
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          cache: sbt
      - name: Install SBT on macOS
        if: runner.os == 'macOS'
        run: brew install sbt
      - name: Run tests
        run: sbt test

  check-code-formatting:
    strategy:
      matrix:
        java-distribution: [temurin]
        java-version: [ 17, 21 ]
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK for scalafmt
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          cache: sbt
      - name: Check scalafmt format
        run: sbt scalafmtCheckAll